var gitusers = 
  [ {
        "login": "andyg72",
        "id": 8938227,
        "avatar_url": "https://avatars.githubusercontent.com/u/8938227?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/andyg72",
        "html_url": "https://github.com/andyg72",
        "followers_url": "https://api.github.com/users/andyg72/followers",
        "following_url": "https://api.github.com/users/andyg72/following{/other_user}",
        "gists_url": "https://api.github.com/users/andyg72/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/andyg72/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/andyg72/subscriptions",
        "organizations_url": "https://api.github.com/users/andyg72/orgs",
        "repos_url": "https://api.github.com/users/andyg72/repos",
        "events_url": "https://api.github.com/users/andyg72/events{/privacy}",
        "received_events_url": "https://api.github.com/users/andyg72/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Andy Newman",
        "company": "",
        "blog": "http://initialdigital.com",
        "location": "London",
        "email": "andygnewman@gmail.com",
        "hireable": false,
        "bio": null,
        "public_repos": 31,
        "public_gists": 0,
        "followers": 14,
        "following": 12,
        "created_at": "2014-09-27T11:46:48Z",
        "updated_at": "2015-02-04T17:41:52Z"
      }, 

  {
    "login": "stepholdcorn",
    "id": 9577604,
    "avatar_url": "https://avatars.githubusercontent.com/u/9577604?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/stepholdcorn",
    "html_url": "https://github.com/stepholdcorn",
    "followers_url": "https://api.github.com/users/stepholdcorn/followers",
    "following_url": "https://api.github.com/users/stepholdcorn/following{/other_user}",
    "gists_url": "https://api.github.com/users/stepholdcorn/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/stepholdcorn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/stepholdcorn/subscriptions",
    "organizations_url": "https://api.github.com/users/stepholdcorn/orgs",
    "repos_url": "https://api.github.com/users/stepholdcorn/repos",
    "events_url": "https://api.github.com/users/stepholdcorn/events{/privacy}",
    "received_events_url": "https://api.github.com/users/stepholdcorn/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Steph Oldcorn",
    "company": "",
    "blog": "",
    "location": "",
    "email": "",
    "hireable": false,
    "bio": null,
    "public_repos": 32,
    "public_gists": 0,
    "followers": 15,
    "following": 15,
    "created_at": "2014-11-05T19:45:44Z",
    "updated_at": "2015-02-04T17:41:52Z"
  }
];

exports.gitusers = gitusers;

